import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :algora, AlgoraWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Algora.Finch

# TODO: Disable Swoosh Local Memory Storage
config :swoosh, local: true

config :logger,
  format: {LogfmtEx, :format},
  level: String.to_atom(System.get_env("LOG_LEVEL") || "info"),
  metadata: :all

config :algora,
  swift_mode: true,
  auto_start_pollers: true

# TODO: remove after migration
config :algora,
  dev_routes: true,
  require_admin_for_mailbox: true

config :algora,
  plausible_url: System.get_env("PLAUSIBLE_URL"),
  assets_url: System.get_env("ASSETS_URL"),
  ingest_url: System.get_env("INGEST_URL")

config :algora, AlgoraWeb.OGImageController, max_age: 600

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
