defmodule AlgoraWeb.Legal.PrivacyLive do
  @moduledoc false
  use AlgoraWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def render(assigns) do
    ~H"""
    <div class="container mx-auto px-4 py-8">
      <main class="h-full overflow-auto">
        <article class="prose mx-auto py-24 prose-invert lg:prose-lg">
          <h1>
            <span>PRIVACY POLICY</span>
          </h1>

          <div>
            <span>Effective date: 08/17/2021</span>
          </div>

          <ol class="list-none pl-0" start={1}>
            <li>
              <span>Introduction</span>
            </li>
          </ol>

          <div>
            <span>Welcome to&nbsp;</span>
            <span>Algora, PBC.</span>
          </div>

          <div>
            <span>
              Algora, PBC.&nbsp;(“us”, “we”, or “our”)
              operates&nbsp;{AlgoraWeb.Endpoint.url()}&nbsp;(hereinafter referred
              to as “
            </span>
            <span>Service</span>
            <span>”).</span>
          </div>

          <div>
            <span>
              Our Privacy Policy governs your visit
              to&nbsp;{AlgoraWeb.Endpoint.url()}, and explains how we collect,
              safeguard and disclose information that results from your use of
              our Service.{" "}
            </span>
          </div>

          <div>
            <span>
              We use your data to provide and improve Service. By using Service,
              you agree to the collection and use of information in accordance
              with this policy. Unless otherwise defined in this Privacy Policy,
              the terms used in this Privacy Policy have the same meanings as in
              our Terms and Conditions.
            </span>
          </div>

          <div>
            <span>Our Terms and Conditions (“</span>
            <span>Terms</span>
            <span>
              ”) govern all use of our Service and together with the Privacy
              Policy constitutes your agreement with us (“
            </span>
            <span>agreement</span>
            <span>”).</span>
          </div>

          <ol class="list-none pl-0" start={2}>
            <li>
              <span>Definitions</span>
            </li>
          </ol>

          <div>
            <span>SERVICE&nbsp;</span>
            <span>
              means the&nbsp;{AlgoraWeb.Endpoint.url()} website&nbsp;operated
              by&nbsp;Algora, PBC.
            </span>
          </div>

          <div>
            <span>PERSONAL DATA</span>
            <span>
              &nbsp;means data about a living individual who can be identified
              from those data (or from those and other information either in our
              possession or likely to come into our possession).
            </span>
          </div>

          <div>
            <span>USAGE DATA</span>
            <span>
              &nbsp;is data collected automatically either generated by the use
              of Service or from Service infrastructure itself (for example, the
              duration of a page visit).
            </span>
          </div>

          <div>
            <span>COOKIES</span>
            <span>
              &nbsp;are small files stored on your device (computer or mobile
              device).
            </span>
          </div>

          <div>
            <span>DATA CONTROLLER</span>
            <span>
              &nbsp;means a natural or legal person who (either alone or jointly
              or in common with other persons) determines the purposes for which
              and the manner in which any personal data are, or are to be,
              processed. For the purpose of this Privacy Policy, we are a Data
              Controller of your data.
            </span>
          </div>

          <div>
            <span>DATA PROCESSORS (OR SERVICE PROVIDERS)</span>
            <span>
              &nbsp;means any natural or legal person who processes the data on
              behalf of the Data Controller. We may use the services of various
              Service Providers in order to process your data more effectively.
            </span>
          </div>

          <div>
            <span>DATA SUBJECT&nbsp;</span>
            <span>
              is any living individual who is the subject of Personal Data.
            </span>
          </div>

          <div>
            <span>THE USER&nbsp;</span>
            <span>
              is the individual using our Service. The User corresponds to the
              Data Subject, who is the subject of Personal Data.
            </span>
          </div>

          <ol class="list-none pl-0" start={3}>
            <li>
              <span>Information Collection and Use</span>
            </li>
          </ol>

          <div>
            <span>
              We collect several different types of information for various
              purposes to provide and improve our Service to you.
            </span>
          </div>

          <ol class="list-none pl-0" start={4}>
            <li>
              <span>Types of Data Collected</span>
            </li>
          </ol>

          <div>
            <span>Personal Data</span>
          </div>
          <div>
            <span>
              While using our Service, we may ask you to provide us with certain
              personally identifiable information that can be used to contact or
              identify you (“
            </span>
            <span>Personal Data</span>
            <span>
              ”). Personally identifiable information may include, but is not
              limited to:
            </span>
          </div>

          <ol class="list-none pl-0" start={1}>
            <li>
              <span>Email address</span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={2}>
            <li>
              <span>First name and last name</span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={3}>
            <li>
              <span>Cookies and Usage Data</span>
            </li>
          </ol>

          <div>
            <span>
              We may use your Personal Data to contact you with newsletters,
              marketing or promotional materials and other information that may
              be of interest to you. You may opt out of receiving any, or all,
              of these communications from us&nbsp;by emailing
              at&nbsp;ioannis@algora.io.
            </span>
          </div>

          <div>
            <span>Usage Data</span>
          </div>
          <div>
            <span>
              We may also collect information that your browser sends whenever
              you visit our Service or when you access Service by or through a
              mobile device (“
            </span>
            <span>Usage Data</span>
            <span>”).</span>
          </div>

          <div>
            <span>
              This Usage Data may include information such as your
              computer&apos;s Internet Protocol address (e.g. IP address),
              browser type, browser version, the pages of our Service that you
              visit, the time and date of your visit, the time spent on those
              pages, unique device identifiers and other diagnostic data.
            </span>
          </div>

          <div>
            <span>
              When you access Service with a mobile device, this Usage Data may
              include information such as the type of mobile device you use,
              your mobile device unique ID, the IP address of your mobile
              device, your mobile operating system, the type of mobile Internet
              browser you use, unique device identifiers and other diagnostic
              data.
            </span>
          </div>

          <div>
            <span>Tracking Cookies Data</span>
          </div>
          <div>
            <span>
              We use cookies and similar tracking technologies to track the
              activity on our Service and we hold certain information.
            </span>
          </div>

          <div>
            <span>
              Cookies are files with a small amount of data which may include an
              anonymous unique identifier. Cookies are sent to your browser from
              a website and stored on your device. Other tracking technologies
              are also used such as beacons, tags and scripts to collect and
              track information and to improve and analyze our Service.
            </span>
          </div>

          <div>
            <span>
              You can instruct your browser to refuse all cookies or to indicate
              when a cookie is being sent. However, if you do not accept
              cookies, you may not be able to use some portions of our Service.
            </span>
          </div>

          <div>
            <span>Examples of Cookies we use:</span>
          </div>

          <ol class="list-none pl-0" start={1}>
            <li>
              <span>Session Cookies:</span>
              <span>&nbsp;We use Session Cookies to operate our Service.</span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={2}>
            <li>
              <span>Preference Cookies:</span>
              <span>
                &nbsp;We use Preference Cookies to remember your preferences and
                various settings.
              </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={3}>
            <li>
              <span>Security Cookies:</span>
              <span>&nbsp;We use Security Cookies for security purposes.</span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={4}>
            <li>
              <span>Advertising Cookies:</span>
              <span>
                &nbsp;Advertising Cookies are used to serve you with
                advertisements that may be relevant to you and your interests.
              </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={5}>
            <li>
              <span>Use of Data</span>
            </li>
          </ol>

          <div>
            <span>
              Algora, PBC.&nbsp;uses the collected data for various purposes:
            </span>
          </div>

          <ol class="list-none pl-0" start={1}>
            <li>
              <span>to provide and maintain our Service;</span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={2}>
            <li>
              <span>to notify you about changes to our Service; </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={3}>
            <li>
              <span>
                to allow you to participate in interactive features of our
                Service when you choose to do so;{" "}
              </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={4}>
            <li>
              <span>to provide customer support; </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={5}>
            <li>
              <span>
                to gather analysis or valuable information so that we can
                improve our Service;{" "}
              </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={6}>
            <li>
              <span>to monitor the usage of our Service;</span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={7}>
            <li>
              <span>to detect, prevent and address technical issues;</span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={8}>
            <li>
              <span>
                to fulfill any other purpose for which you provide it;
              </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={9}>
            <li>
              <span>
                to carry out our obligations and enforce our rights arising from
                any contracts entered into between you and us, including for
                billing and collection;
              </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={10}>
            <li>
              <span>
                to provide you with notices about your account and/or
                subscription, including expiration and renewal notices,
                email-instructions, etc.;
              </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={11}>
            <li>
              <span>
                to provide you with news, special offers and general information
                about other goods, services and events which we offer that are
                similar to those that you have already purchased or enquired
                about unless you have opted not to receive such information;
              </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={12}>
            <li>
              <span>
                in any other way we may describe when you provide the
                information;
              </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={13}>
            <li>
              <span>for any other purpose with your consent. </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={6}>
            <li>
              <span>Retention of Data</span>
            </li>
          </ol>

          <div>
            <span>
              We will retain your Personal Data only for as long as is necessary
              for the purposes set out in this Privacy Policy. We will retain
              and use your Personal Data to the extent necessary to comply with
              our legal obligations (for example, if we are required to retain
              your data to comply with applicable laws), resolve disputes, and
              enforce our legal agreements and policies.
            </span>
          </div>

          <div>
            <span>
              We will also retain Usage Data for internal analysis purposes.
              Usage Data is generally retained for a shorter period, except when
              this data is used to strengthen the security or to improve the
              functionality of our Service, or we are legally obligated to
              retain this data for longer time periods.
            </span>
          </div>

          <ol class="list-none pl-0" start={7}>
            <li>
              <span>Transfer of Data</span>
            </li>
          </ol>

          <div>
            <span>
              Your information, including Personal Data, may be transferred to –
              and maintained on – computers located outside of your state,
              province, country or other governmental jurisdiction where the
              data protection laws may differ from those of your jurisdiction.
            </span>
          </div>

          <div>
            <span>
              If you are located outside United States and choose to provide
              information to us, please note that we transfer the data,
              including Personal Data, to United States and process it there.
            </span>
          </div>

          <div>
            <span>
              Your consent to this Privacy Policy followed by your submission of
              such information represents your agreement to that transfer.
            </span>
          </div>

          <div>
            <span>
              Algora, PBC.&nbsp;will take all the steps reasonably necessary to
              ensure that your data is treated securely and in accordance with
              this Privacy Policy and no transfer of your Personal Data will
              take place to an organisation or a country unless there are
              adequate controls in place including the security of your data and
              other personal information.
            </span>
          </div>

          <ol class="list-none pl-0" start={8}>
            <li>
              <span>Disclosure of Data</span>
            </li>
          </ol>

          <div>
            <span>
              We may disclose personal information that we collect, or you
              provide:
            </span>
          </div>

          <ol class="list-none pl-0" start={1}>
            <li>
              <span>Disclosure for Law Enforcement.</span>
            </li>
          </ol>
          <div>
            <span>
              Under certain circumstances, we may be required to disclose your
              Personal Data if required to do so by law or in response to valid
              requests by public authorities.
            </span>
          </div>

          <ol class="list-none pl-0" start={2}>
            <li>
              <span>Business Transaction.</span>
            </li>
          </ol>
          <div>
            <span>
              If we or our subsidiaries are involved in a merger, acquisition or
              asset sale, your Personal Data may be transferred.
            </span>
          </div>

          <ol class="list-none pl-0" start={3}>
            <li>
              <span>Other cases. We may disclose your information also:</span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={1}>
            <li>
              <span>to our subsidiaries and affiliates;</span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={2}>
            <li>
              <span>
                to contractors, service providers, and other third parties we
                use to support our business;
              </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={3}>
            <li>
              <span>to fulfill the purpose for which you provide it;</span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={4}>
            <li>
              <span>
                for the purpose of including your company’s logo on our website;
              </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={5}>
            <li>
              <span>
                for any other purpose disclosed by us when you provide the
                information;
              </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={6}>
            <li>
              <span>with your consent in any other cases;</span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={7}>
            <li>
              <span>
                if we believe disclosure is necessary or appropriate to protect
                the rights, property, or safety of the Company, our customers,
                or others.
              </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={9}>
            <li>
              <span>Security of Data</span>
            </li>
          </ol>

          <div>
            <span>
              The security of your data is important to us but remember that no
              method of transmission over the Internet or method of electronic
              storage is 100% secure. While we strive to use commercially
              acceptable means to protect your Personal Data, we cannot
              guarantee its absolute security.
            </span>
          </div>

          <ol class="list-none pl-0" start={10}>
            <li>
              <span>
                Your Data Protection Rights Under General Data Protection
                Regulation (GDPR)
              </span>
            </li>
          </ol>

          <div>
            <span>
              If you are a resident of the European Union (EU) and European
              Economic Area (EEA), you have certain data protection rights,
              covered by GDPR. – See more at
              https://eur-lex.europa.eu/eli/reg/2016/679/oj{" "}
            </span>
          </div>

          <div>
            <span>
              We aim to take reasonable steps to allow you to correct, amend,
              delete, or limit the use of your Personal Data.
            </span>
          </div>

          <div>
            <span>
              If you wish to be informed what Personal Data we hold about you
              and if you want it to be removed from our systems, please email us
              at ioannis@algora.io.{" "}
            </span>
          </div>

          <div>
            <span>
              In certain circumstances, you have the following data protection
              rights:
            </span>
          </div>

          <ol class="list-none pl-0" start={1}>
            <li>
              <span>
                the right to access, update or to delete the information we have
                on you;
              </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={2}>
            <li>
              <span>
                the right of rectification. You have the right to have your
                information rectified if that information is inaccurate or
                incomplete;
              </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={3}>
            <li>
              <span>
                the right to object. You have the right to object to our
                processing of your Personal Data;
              </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={4}>
            <li>
              <span>
                the right of restriction. You have the right to request that we
                restrict the processing of your personal information;
              </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={5}>
            <li>
              <span>
                the right to data portability. You have the right to be provided
                with a copy of your Personal Data in a structured,
                machine-readable and commonly used format;
              </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={6}>
            <li>
              <span>
                the right to withdraw consent.&nbsp;You also have the right to
                withdraw your consent at any time where we rely on your consent
                to process your personal information;
              </span>
            </li>
          </ol>

          <div>
            <span>
              Please note that we may ask you to verify your identity before
              responding to such requests. Please note, we may not able to
              provide Service without some necessary data.
            </span>
          </div>

          <div>
            <span>
              You have the right to complain to a Data Protection Authority
              about our collection and use of your Personal Data. For more
              information, please contact your local data protection authority
              in the European Economic Area (EEA).
            </span>
          </div>

          <ol class="list-none pl-0" start={11}>
            <li>
              <span>
                Your Data Protection Rights under the California Privacy
                Protection Act (CalOPPA)
              </span>
            </li>
          </ol>

          <div>
            <span>
              CalOPPA is the first state law in the nation to require commercial
              websites and online services to post a privacy policy. The law’s
              reach stretches well beyond California to require a person or
              company in the United States (and conceivable the world) that
              operates websites collecting personally identifiable information
              from California consumers to post a conspicuous privacy policy on
              its website stating exactly the information being collected and
              those individuals with whom it is being shared, and to comply with
              this policy. – See more at:
              https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/{" "}
            </span>
          </div>

          <div>
            <span>According to CalOPPA we agree to the following:</span>
          </div>

          <ol class="list-none pl-0" start={1}>
            <li>
              <span>users can visit our site anonymously;</span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={2}>
            <li>
              <span>
                our Privacy Policy link includes the word “Privacy”, and can
                easily be found on the page specified above on the home page of
                our website;
              </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={3}>
            <li>
              <span>
                users will be notified of any privacy policy changes on our
                Privacy Policy Page;
              </span>
            </li>
          </ol>

          <ol class="list-none pl-0" start={4}>
            <li>
              <span>
                users are able to change their personal information by emailing
                us at ioannis@algora.io.{" "}
              </span>
            </li>
          </ol>

          <div>
            <span>Our Policy on “Do Not Track” Signals:</span>
          </div>

          <div>
            <span>
              We honor Do Not Track signals and do not track, plant cookies, or
              use advertising when a Do Not Track browser mechanism is in place.
              Do Not Track is a preference you can set in your web browser to
              inform websites that you do not want to be tracked.{" "}
            </span>
          </div>

          <div>
            <span>
              You can enable or disable Do Not Track by visiting the Preferences
              or Settings page of your web browser.
            </span>
          </div>

          <ol class="list-none pl-0" start={12}>
            <li>
              <span>Service Providers</span>
            </li>
          </ol>

          <div>
            <span>
              We may employ third party companies and individuals to facilitate
              our Service (“
            </span>
            <span>Service Providers</span>
            <span>
              ”), provide Service on our behalf, perform Service-related
              services or assist us in analysing how our Service is used.
            </span>
          </div>

          <div>
            <span>
              These third parties have access to your Personal Data only to
              perform these tasks on our behalf and are obligated not to
              disclose or use it for any other purpose.
            </span>
          </div>

          <ol class="list-none pl-0" start={13}>
            <li>
              <span>Payments</span>
            </li>
          </ol>

          <div>
            <span>
              We may provide paid products and/or services within Service. In
              that case, we use third-party services for payment processing
              (e.g. payment processors).
            </span>
          </div>

          <div>
            <span>
              We will not store or collect your payment card details. That
              information is provided directly to our third-party payment
              processors whose use of your personal information is governed by
              their Privacy Policy. These payment processors adhere to the
              standards set by PCI-DSS as managed by the PCI Security Standards
              Council, which is a joint effort of brands like Visa, Mastercard,
              American Express and Discover. PCI-DSS requirements help ensure
              the secure handling of payment information.
            </span>
          </div>

          <div>
            <span>The payment processors we work with are:</span>
          </div>

          <div>
            <span>Stripe:</span>
          </div>
          <div>
            <span>
              Their Privacy Policy can be viewed at:
              https://stripe.com/us/privacy
            </span>
          </div>

          <div>
            <span>Plaid:</span>
          </div>
          <div>
            <span>
              Their End User Privacy Policy, Cookie Policy and Privacy Statement
              can be viewed at https://plaid.com/legal/.
            </span>
          </div>

          <ol class="list-none pl-0" start={14}>
            <li>
              <span>Links to Other Sites</span>
            </li>
          </ol>

          <div>
            <span>
              Our Service may contain links to other sites that are not operated
              by us. If you click a third party link, you will be directed to
              that third party&apos;s site. We strongly advise you to review the
              Privacy Policy of every site you visit.
            </span>
          </div>

          <div>
            <span>
              We have no control over and assume no responsibility for the
              content, privacy policies or practices of any third party sites or
              services.
            </span>
          </div>

          <ol class="list-none pl-0" start={15}>
            <li>
              <span>Children&apos;s Privacy</span>
            </li>
          </ol>

          <div>
            <span>
              Our Services are not intended for use by children under the age of
              18 (“
            </span>
            <span>Child</span>
            <span>” or “</span>
            <span>Children</span>
            <span>”). </span>
          </div>

          <div>
            <span>
              We do not knowingly collect personally identifiable information
              from Children under 18. If you become aware that a Child has
              provided us with Personal Data, please contact us. If we become
              aware that we have collected Personal Data from Children without
              verification of parental consent, we take steps to remove that
              information from our servers.
            </span>
          </div>

          <ol class="list-none pl-0" start={16}>
            <li>
              <span>Changes to This Privacy Policy</span>
            </li>
          </ol>

          <div>
            <span>
              We may update our Privacy Policy from time to time. We will notify
              you of any changes by posting the new Privacy Policy on this page.
            </span>
          </div>

          <div>
            <span>
              We will let you know via email and/or a prominent notice on our
              Service, prior to the change becoming effective and update
              “effective date” at the top of this Privacy Policy.
            </span>
          </div>

          <div>
            <span>
              You are advised to review this Privacy Policy periodically for any
              changes. Changes to this Privacy Policy are effective when they
              are posted on this page.
            </span>
          </div>

          <ol class="list-none pl-0" start={17}>
            <li>
              <span>Contact Us</span>
            </li>
          </ol>

          <div>
            <span>
              If you have any questions about this Privacy Policy, please
              contact us:
            </span>
          </div>

          <div>
            <span>By email: ioannis@algora.io.</span>
          </div>
        </article>
      </main>
    </div>
    """
  end
end
